-- ref_specialty_bridge (statement 3/3): insert one row per distinct granular
-- specialty token in nfhs_condition_symptom_specialty_map.tsv (30 tokens,
-- 29 real + NO_SPECIALTY_MATCH). Canonical clinical mapping per the BRIDGE spec.
INSERT INTO workspace.app_state.ref_specialty_bridge (granular_specialty, ui_discipline) VALUES
  ('internalmedicine',                              'General Medicine'),
  ('familymedicine',                                'General Medicine'),
  ('generalmedicine',                               'General Medicine'),
  ('preventivemedicine',                            'General Medicine'),
  ('chronicdiseasepreventionandlifestylemedicine',  'General Medicine'),
  ('infectiousdiseases',                            'General Medicine'),
  ('gastroenterology',                              'General Medicine'),
  ('pulmonology',                                   'General Medicine'),
  ('hematology',                                    'General Medicine'),
  ('endocrinologyanddiabetesandmetabolism',         'General Medicine'),
  ('cardiology',                                    'Cardiology'),
  ('nephrology',                                    'Nephrology'),
  ('pediatrics',                                    'Pediatrics'),
  ('pediatriccriticalcaremedicine',                 'Pediatrics'),
  ('neonatologyperinatalmedicine',                  'Pediatrics'),
  ('gynecologyandobstetrics',                       'Obstetrics'),
  ('obstetricsandmaternitycare',                    'Obstetrics'),
  ('maternalfetalmedicineorperinatology',           'Obstetrics'),
  ('familyplanningandcomplexcontraception',         'Obstetrics'),
  ('reproductiveendocrinologyandinfertility',       'Obstetrics'),
  ('medicaloncology',                               'Oncology'),
  ('surgicaloncology',                              'Oncology'),
  ('gynecologiconcology',                           'Oncology'),
  ('emergencymedicine',                             'Trauma'),
  ('bariatricsurgery',                              NULL),
  ('psychiatry',                                    NULL),
  ('otolaryngology',                                NULL),
  ('oralandmaxillofacialsurgery',                   NULL),
  ('dentistry',                                     NULL),
  ('NO_SPECIALTY_MATCH',                            NULL)
