// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    atlas_district_health: {
        name: "atlas_district_health";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          nfhs_district: string;
          /** @sqlType STRING */
          state_ut: string;
          /** @sqlType DOUBLE */
          ncd: number;
          /** @sqlType DOUBLE */
          anaemia: number;
          /** @sqlType DOUBLE */
          malnutrition: number;
          /** @sqlType DOUBLE */
          womensnut: number;
          /** @sqlType DOUBLE */
          acutechild: number;
          /** @sqlType DOUBLE */
          cancerscreen: number;
          /** @sqlType DOUBLE */
          riskfactors: number;
        }>;
      };
    atlas_state_health: {
        name: "atlas_state_health";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType DOUBLE */
          ncd: number;
          /** @sqlType DOUBLE */
          anaemia: number;
          /** @sqlType DOUBLE */
          malnutrition: number;
          /** @sqlType DOUBLE */
          womensnut: number;
          /** @sqlType DOUBLE */
          acutechild: number;
          /** @sqlType DOUBLE */
          cancerscreen: number;
          /** @sqlType DOUBLE */
          riskfactors: number;
          /** @sqlType BIGINT */
          district_count: number;
        }>;
      };
    desert_rank: {
        name: "desert_rank";
        parameters: {
          /** INT - use sql.int() */
          limit: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          nfhs_district: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
          /** @sqlType DOUBLE */
          need_score: number;
          /** @sqlType DOUBLE */
          supply_scarcity: number;
          /** @sqlType DOUBLE */
          desert_score: number;
          /** @sqlType BIGINT */
          desert_rank: number;
        }>;
      };
    district_demand_for: {
        name: "district_demand_for";
        parameters: {
          /** STRING - use sql.string() */
          nfhs_district: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          nfhs_district: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          discipline: string;
          /** @sqlType DOUBLE */
          demand_score: number;
          /** @sqlType STRING */
          top_driver: string;
        }>;
      };
    facilities_by_state: {
        name: "facilities_by_state";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facilities_in_radius: {
        name: "facilities_in_radius";
        parameters: {
          /** DOUBLE - use sql.double() */
          lat: SQLNumberMarker;
          /** DOUBLE - use sql.double() */
          lng: SQLNumberMarker;
          /** DOUBLE - use sql.double() */
          radius_km: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          type: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType DOUBLE */
          lat: number;
          /** @sqlType DOUBLE */
          lng: number;
          /** @sqlType ARRAY<STRING> */
          specialties: unknown[];
          /** @sqlType ARRAY<STRING> */
          needs: unknown[];
          /** @sqlType STRING */
          trust: string;
          /** @sqlType INT */
          conf: number;
          /** @sqlType INT */
          beds: number;
          /** @sqlType BIGINT */
          pincode: number;
          /** @sqlType STRING */
          district: string;
          /** @sqlType DOUBLE */
          distance_km: number;
        }>;
      };
    facilities_search: {
        name: "facilities_search";
        parameters: {
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          type: SQLStringMarker;
          /** STRING - use sql.string() */
          trust: SQLStringMarker;
          /** STRING - use sql.string() */
          q: SQLStringMarker;
          /** INT - use sql.int() */
          limit: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          type: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType DOUBLE */
          lat: number;
          /** @sqlType DOUBLE */
          lng: number;
          /** @sqlType ARRAY<STRING> */
          specialties: unknown[];
          /** @sqlType ARRAY<STRING> */
          needs: unknown[];
          /** @sqlType STRING */
          trust: string;
          /** @sqlType INT */
          conf: number;
          /** @sqlType INT */
          beds: number;
          /** @sqlType INT */
          year: number;
          /** @sqlType BIGINT */
          pincode: number;
          /** @sqlType STRING */
          district: string;
          /** @sqlType BOOLEAN */
          data_quality_flag: boolean;
        }>;
      };
    facility_detail: {
        name: "facility_detail";
        parameters: {
          /** STRING - use sql.string() */
          facility_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          type: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType DOUBLE */
          lat: number;
          /** @sqlType DOUBLE */
          lng: number;
          /** @sqlType ARRAY<STRING> */
          specialties: unknown[];
          /** @sqlType ARRAY<STRING> */
          specialties_detail: unknown[];
          /** @sqlType ARRAY<STRING> */
          needs: unknown[];
          /** @sqlType STRING */
          trust: string;
          /** @sqlType INT */
          conf: number;
          /** @sqlType INT */
          beds: number;
          /** @sqlType INT */
          year: number;
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          procedure: string;
          /** @sqlType STRING */
          equipment: string;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          evidence: string;
          /** @sqlType ARRAY<STRUCT<TEXT:STRING,STATUS:STRING>> */
          claims: unknown[];
          /** @sqlType BIGINT */
          pincode: number;
          /** @sqlType STRING */
          district: string;
          /** @sqlType BOOLEAN */
          data_quality_flag: boolean;
          /** @sqlType BOOLEAN */
          possible_entity_dup: boolean;
          /** @sqlType BOOLEAN */
          id_valid: boolean;
          /** @sqlType STRING */
          coord_source: string;
        }>;
      };
    facility_kpis: {
        name: "facility_kpis";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_facilities: number;
          /** @sqlType BIGINT */
          states: number;
          /** @sqlType BIGINT */
          districts: number;
          /** @sqlType BIGINT */
          claimed_facilities: number;
          /** @sqlType BIGINT */
          unverified_facilities: number;
        }>;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** STRING - use sql.string() */
          message: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** INT - use sql.int() */
          max_month_num: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType INT */
          month_num: number;
          /** @sqlType INT */
          revenue: number;
          /** @sqlType INT */
          expenses: number;
          /** @sqlType INT */
          customers: number;
        }>;
      };
    registry_field_coverage: {
        name: "registry_field_coverage";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_facilities: number;
          /** @sqlType DECIMAL(26,1) */
          description_pct: number;
          /** @sqlType DECIMAL(26,1) */
          capability_pct: number;
          /** @sqlType DECIMAL(26,1) */
          procedure_pct: number;
          /** @sqlType DECIMAL(26,1) */
          equipment_pct: number;
          /** @sqlType DECIMAL(26,1) */
          beds_pct: number;
          /** @sqlType DECIMAL(26,1) */
          year_pct: number;
        }>;
      };
    state_coverage_all: {
        name: "state_coverage_all";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
          /** @sqlType DOUBLE */
          coverage_index: number;
        }>;
      };
    symptom_specialties: {
        name: "symptom_specialties";
        parameters: {
          /** STRING - use sql.string() */
          symptom: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          symptom: string;
          /** @sqlType STRING */
          discipline: string;
          /** @sqlType STRING */
          source_condition: string;
          /** @sqlType STRING */
          source_indicator: string;
          /** @sqlType STRING */
          confidence: string;
        }>;
      };
  }
}
